# ??? DataSource ???????????????????????????????????????????????
spring.datasource.url=jdbc:postgresql://db.ywppeftitcbqfjypgmhd.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=3rd1stGroupP

# ??? Connection Pool (HikariCP) ???????????????????????????????
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

# ??? JPA / Hibernate ??????????????????????????????????????????
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ??? SSL (required by Supabase) ???????????????????????????????
spring.datasource.hikari.data-source-properties.sslmode=require