# ??? DataSource ???????????????????????????????????????????????
spring.datasource.url=jdbc:postgresql://db.ywppeftitcbqfjypgmhd.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=3rd1stGroupP

# ??? Connection Pool (HikariCP) ???????????????????????????????
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

# ??? JPA / Hibernate ??????????????????????????????????????????
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ??? SSL (required by Supabase) ???????????????????????????????
spring.datasource.hikari.data-source-properties.sslmode=require

# File Upload (for ticket attachments)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB

#  Server
server.port=8080

# OAuth2 / Google Login
spring.security.oauth2.client.registration.google.client-id=244436492636-6ftp1vjingl0c33gaetpvi1ff778uhqv.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# File Upload Directory
file.upload-dir=uploads
# Enable data.sql execution on startup
spring.sql.init.mode=always

spring.jpa.defer-datasource-initialization=true
